import { AudioLines, ListChecks, Sparkles, Waves } from "lucide-react";
import { redirect } from "next/navigation";
import { LoginButtons } from "@/components/shell/login-buttons";
import { auth } from "@/lib/auth";
import { hasGoogle } from "@/lib/env";

const FEATURES = [
  { icon: AudioLines, title: "Record & transcribe", body: "Capture a live call in the browser and watch the transcript appear word by word, with speakers separated." },
  { icon: Sparkles, title: "AI notes that cite", body: "Overview, chapters and action items generated by Claude — then ask follow-up questions and jump to the exact moment." },
  { icon: ListChecks, title: "Nothing gets lost", body: "Every commitment becomes a task. Every number becomes searchable across your whole workspace." },
];

export default async function LoginPage() {
  const session = await auth();
  if (session?.user) redirect("/home");

  return (
    <main className="flex min-h-screen">
      <div className="flex w-full flex-col justify-center px-6 py-12 sm:px-12 lg:w-[46%] lg:px-16">
        <div className="mx-auto w-full max-w-sm">
          <div className="mb-8 flex items-center gap-2.5">
            <span className="flex size-9 items-center justify-center rounded-xl bg-brand-600 text-base font-bold text-white">
              F
            </span>
            <span className="text-[15px] font-semibold text-ink-900">FireflyX</span>
          </div>

          <h1 className="text-2xl font-semibold tracking-tight text-ink-900">
            Your meetings, searchable.
          </h1>
          <p className="mt-2 text-[13.5px] leading-relaxed text-ink-500">
            Sign in to record, transcribe and summarize your calls.
          </p>

          <div className="mt-7">
            <LoginButtons googleEnabled={hasGoogle()} />
          </div>

          <p className="mt-6 text-[12px] leading-relaxed text-ink-400">
            The demo gives you your own private workspace, pre-loaded with three fully
            transcribed meetings. Record, edit and delete freely — nobody else sees it.
          </p>
        </div>
      </div>

      <div className="relative hidden flex-1 overflow-hidden border-l border-line bg-gradient-to-br from-brand-50 via-white to-ink-50 lg:block">
        <div className="flex h-full flex-col justify-center gap-7 px-14">
          {FEATURES.map(({ icon: Icon, title, body }) => (
            <div key={title} className="flex max-w-md gap-3.5">
              <span className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-lg bg-white text-brand-600 shadow-sm ring-1 ring-line">
                <Icon className="size-4" />
              </span>
              <div>
                <p className="text-[14px] font-semibold text-ink-900">{title}</p>
                <p className="mt-1 text-[13px] leading-relaxed text-ink-500">{body}</p>
              </div>
            </div>
          ))}
        </div>
        <Waves className="pointer-events-none absolute -bottom-16 -right-10 size-72 text-brand-200/40" />
      </div>
    </main>
  );
}
